inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop/strict.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: true
  NewCops: enable
  TargetRubyVersion: 3.1.1

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: true
  Exclude:
    - "**/config/environments/**/*"
    - "**/config/application.rb"
    - "**/config/environment.rb"
    - "**/config/puma.rb"
    - "**/config/boot.rb"
    - "**/spec/*_helper.rb"
    - "**/spec/**/support/**/*"
    - "lib/generators/**/*"

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact
  Exclude:
    - "**/config/application.rb"
